# https://www.sciencedirect.com/science/article/pii/S2667318522000071
# Adapted from Table 5 DistMult on Hetionet (OpenBioLink not in the study)

model:
  name: DistMult
  embedding_dim: 80

optimizer:
  class: Adagrad
  lr: 0.02

train:
  loss_function: MarginRankingLoss
  num_epoch: 400
  num_negative: 41
  create_inverse: False

save:
  path: openbiolink

seed: 42
